### ISSUE TITLE
[REST] ToDo list for controllers

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#128]
- [x] /user/login
- [x] /user/register
- [x] /user/update #129
- [x] /user/follow #130
- [x] /user/get #131
- [x] /user/stories #132
- [x] /search #133
- [x] /story/get https://github.com/bounswe/bounswe2015group7/issues/112
- [x] /story/create https://github.com/bounswe/bounswe2015group7/issues/112
- [x] /story/report #144 #139
- [x] /story/vote #145
- [x] /story/edit #151
- [x] /story/similar
- [x] /tag/get #146
- [x] /tag/edit
- [x] /comment/new #149 
- [x] /comment/edit #150 
- [x] /comment/get #135
- [x] /comment/list #136
- [x] /recommendation/basedOnFollowedStories
- [x] /recommendation/basedOnFollowedUser
- [x] /media/upload /media/get  #152
